app_core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path, re_path

from apps.common.utils.views import handler400 as h400
from apps.common.utils.views import handler403 as h403
from apps.common.utils.views import handler404 as h404
from apps.common.utils.views import handler500 as h500

admin_url = settings.ADMIN_URL
custom_apps = settings.CUSTOM_APPS
utils_path = settings.UTILS_PATH

apps_urls = [path('', include(f'{app}.urls')) for app in custom_apps]

handler400 = h400

handler403 = h403

handler404 = h404

handler500 = h500

third_party_urls = [
    re_path(
        r'^rosetta/',
        include('rosetta.urls')
    ),
]

admin_urls = [
    path(admin_url, admin.site.urls),
]

urlpatterns = admin_urls + apps_urls + third_party_urls

if settings.DEBUG:
    urlpatterns += static(
        settings.STATIC_URL,
        document_root=settings.STATIC_ROOT
    )
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )

apps/project/specific/certificates/urls.py
from django.urls import path

from .views import CertificateInputView, CertificateDetailView, CertificateListView, CertificateFormFacadeTemplateView, LockoutTimeView

app_name = 'certificates'

urlpatterns = [
    path('certificate/', CertificateInputView.as_view(), name='input'),
    path('certificate/form/', CertificateFormFacadeTemplateView.as_view(), name='form'),
    path('certificate/<uuid:pk>/', CertificateDetailView.as_view(), name='detail'),
    path('certificate/list/', CertificateListView.as_view(), name='list'),
    path('lockout-time/', LockoutTimeView.as_view(), name='lockout_time'),
]

apps/project/specific/certificates/models.py
import uuid

from django.db import models
from django.utils.translation import gettext_lazy as _

from apps.common.utils.models import TimeStampedModel


class CertificateModel(TimeStampedModel):
    class DocumentTypeChoices(models.TextChoices):
        CC = 'CC', _('Citizen ID (CC)')
        CE = 'CE', _('Foreigner ID (CE)')
        PPT = 'PPT', _('Special Residence Permit (PPT)')
        TI = 'TI', _('Identity Card (TI)')
        PA = 'PA', _('Passport (PA)')
        RC = 'RC', _('Civil Registry (RC)')
        NIT = 'NIT', _('Tax Identification Number (NIT)')
        RUT = 'RUT', _('Single Tax Registry (RUT)')
        CD = 'CD', _('Diplomatic ID Card (CD)')

    id = models.UUIDField(
        'ID',
        default=uuid.uuid4,
        unique=True,
        primary_key=True,
        serialize=False,
        editable=False
    )

    name = models.CharField(
        _('Name'),
        max_length=100
    )

    document_type = models.CharField(
        _('Document type'),
        max_length=4,
        choices=DocumentTypeChoices.choices,
        default=DocumentTypeChoices.CC
    )

    document_number = models.CharField(
        _('Document number'),
        max_length=20,
    )

    step = models.IntegerField(
        _('Step'),
        default=1,
        help_text=_('Step of the certificate')
    )

    approved = models.BooleanField(
        _('Approved'),
        default=True,
    )

    def masked_document_number(self):
        """Returns the ID number with all but the last four digits masked."""
        document_number_str = str(self.document_number)
        last_four = document_number_str[-4:]
        masked = '*' * (len(document_number_str) - 4) + last_four
        return masked
    
    def save(self, *args, **kwargs):
        self.name = self.name.upper()
        super().save(*args, **kwargs)

    def __str__(self):
        return f'{self.name} {self.masked_document_number()}'

    class Meta:
        db_table = "apps_project_specific_certificates_certificate"
        verbose_name = _("Certificate")
        verbose_name_plural = _("Certificates")
        ordering = ["default_order", "-created"]
        unique_together = ['document_number', 'document_type']
        permissions = [
            ('view_certificate', 'Can view certificate list'),
        ]

apps/project/specific/certificates/forms.py
import re

from django import forms
from django.utils.translation import gettext_lazy as _

from .models import CertificateModel


class IDNumberForm(forms.Form):

    document_type = forms.ChoiceField(
        label=_("Document Type"),
        choices=CertificateModel.DocumentTypeChoices.choices,
        initial=CertificateModel.DocumentTypeChoices.CC
    )

    document_number = forms.CharField(
        label=_('Document Number'),
        max_length=50
    )

    def clean_document_number(self):
        document_number = self.cleaned_data['document_number']
        document_number = re.sub(r'\D', '', document_number)
        return document_number

apps/project/specific/certificates/views.py
import base64
from datetime import timedelta
from io import BytesIO

import barcode
import qrcode
import requests
from barcode.writer import ImageWriter
from django.contrib import messages
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.db.models import Q
from django.http import JsonResponse
from django.shortcuts import redirect
from django.utils import timezone
from django.utils.safestring import mark_safe
from django.utils.translation import gettext_lazy as _
from django.views.generic import (DetailView, FormView, ListView, TemplateView,
                                  View)
from PIL import Image

from .forms import IDNumberForm
from .models import CertificateModel


class CertificateFormFacadeTemplateView(TemplateView):
    template_name = 'certificate_form_facade.html'


class LockoutTimeView(View):
    def get(self, request):
        lockout_time = request.session.get('lockout_time')
        if lockout_time:
            lockout_time = timezone.make_aware(
                timezone.datetime.fromtimestamp(lockout_time))
            lockout_duration = timedelta(minutes=60)
            if timezone.now() < lockout_time + lockout_duration:
                remaining_time = (
                    lockout_time + lockout_duration - timezone.now()).seconds
                return JsonResponse({'remaining_time': remaining_time})

        return JsonResponse({'remaining_time': 0})


class CertificateInputView(FormView):
    template_name = 'certificate_input.html'
    form_class = IDNumberForm

    def form_valid(self, form):
        max_attempts = 5
        lockout_duration = timedelta(minutes=60)
        failed_attempts = self.request.session.get('failed_attempts', 0)
        lockout_time = self.request.session.get('lockout_time')
        if lockout_time:
            lockout_time = timezone.make_aware(
                timezone.datetime.fromtimestamp(lockout_time))
            if timezone.now() < lockout_time + lockout_duration:
                messages.error(
                    self.request,
                    _('Too many failed attempts.')
                )
                return self.form_invalid(form)
            else:
                self.request.session['failed_attempts'] = 0
                self.request.session['lockout_time'] = None

        document_type = form.cleaned_data['document_type']
        document_number = form.cleaned_data['document_number']

        try:
            certificate = CertificateModel.objects.get(
                document_type=document_type,
                document_number=document_number
            )
            self.request.session['failed_attempts'] = 0
            self.request.session['lockout_time'] = None
            return redirect('certificates:detail', pk=certificate.id)

        except CertificateModel.DoesNotExist:
            failed_attempts += 1
            self.request.session['failed_attempts'] = failed_attempts
            if failed_attempts >= max_attempts:
                self.request.session['lockout_time'] = timezone.now(
                ).timestamp()
                messages.error(
                    self.request, _(
                        'Too many failed attempts.'
                    )
                )
            else:
                form.add_error('document_number', _('ID Number not found.'))
            return self.form_invalid(form)


class CertificateDetailView(DetailView):
    model = CertificateModel
    template_name = 'certificate_detail.html'
    context_object_name = 'certificate'

    def generate_qr_with_favicon(self, url):
        # Crear el código QR
        qr = qrcode.QRCode(
            version=1,
            error_correction=qrcode.constants.ERROR_CORRECT_H,
            box_size=10,
            border=4,
        )
        qr.add_data(url)
        qr.make(fit=True)

        img_qr = qr.make_image(fill="black", back_color="white").convert("RGB")

        # Insertar favicon en el centro
        icon_url = "https://cbh.fundacionleirion.com/static/imgs/favicon/android-chrome-512x512.png"
        response = requests.get(icon_url)
        icon = Image.open(BytesIO(response.content))
        
        icon = icon.resize((img_qr.size[0] // 4, img_qr.size[1] // 4), Image.LANCZOS)
        pos = ((img_qr.size[0] - icon.size[0]) // 2, (img_qr.size[1] - icon.size[1]) // 2)
        img_qr.paste(icon, pos, icon)

        buffer = BytesIO()
        img_qr.save(buffer, format="PNG")
        qr_base64 = base64.b64encode(buffer.getvalue()).decode()
        return f"data:image/png;base64,{qr_base64}"

    def generate_barcode(self, uuid_str):
        buffer = BytesIO()
        barcode_class = barcode.get_barcode_class('code128')
        barcode_image = barcode_class(uuid_str, writer=ImageWriter())
        barcode_image.write(buffer)
        barcode_base64 = base64.b64encode(buffer.getvalue()).decode()
        return f"data:image/png;base64,{barcode_base64}"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        certificate_url = "https://cbh.fundacionleirion.com/certificate/{}".format(
            self.object.pk
        )

        # Generar códigos bajo demanda
        context['qr_code'] = mark_safe(
            self.generate_qr_with_favicon(certificate_url)
        )
        context['barcode'] = mark_safe(
            self.generate_barcode(str(self.object.pk))
        )
        return context


class CertificateListView(PermissionRequiredMixin, ListView):
    model = CertificateModel
    template_name = 'certificate_list.html'
    context_object_name = 'certificates'
    permission_required = ('certificates.view_certificate',)

    def has_permission(self):
        return self.request.user.is_superuser or super().has_permission()

    def get_queryset(self):
        queryset = super().get_queryset()
        search_query = self.request.GET.get('q', '')
        order_by = self.request.GET.get('order_by', 'default_order')
        order_dir = self.request.GET.get('order_dir', 'asc')
        step_filter = self.request.GET.get('step', None)
        approved_filter = self.request.GET.get('approved', None)

        if search_query:
            queryset = queryset.filter(
                Q(name__icontains=search_query) |
                Q(document_number__icontains=search_query)
            )

        if step_filter:
            queryset = queryset.filter(step=step_filter)

        if approved_filter is not None:
            if approved_filter == 'true':
                queryset = queryset.filter(approved=True)
            elif approved_filter == 'false':
                queryset = queryset.filter(approved=False)

        if order_dir == 'desc':
            order_by = f'-{order_by}'
        queryset = queryset.order_by(order_by)

        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['total_displayed'] = self.get_queryset().count()
        context['order_by'] = self.request.GET.get('order_by', 'default_order')
        context['order_dir'] = self.request.GET.get('order_dir', 'asc')
        return context

apps/project/specific/certificates/templates/certificate_base.html
{% extends 'base.html' %}

{% load static i18n %}

{% block meta %}
    <meta charset="UTF-8">
    <meta http-equiv="PRAGMA" content="NO-CACHE" />
    <meta content="width=device-width, initial-scale=1.0" name="viewport"/>
    <meta content="text/html; charset=utf-8" http-equiv="Content-Type" />
    <meta content="{% trans 'Certificates | Fundación Leirion' %}" name="title" />
    <meta content="{% trans 'Certificates | Fundación Leirion' %}" property="og:title" />
    <meta content="{% static 'imgs/favicon/favicon-16x16.png' %}" property="og:image"/>
    <meta content="https://cbh.fundacionleirion.com/" property="og:url" />
    <meta content="Fundación Leirion" property="og:site_name" />
    <meta content="{% trans 'Fundación Leirion certificates' %}" property="og:description"/>
    <meta content="{% trans 'Fundación Leirion certificates' %}" name="description" />
{% endblock meta %}

{% block header %}
    {% include 'partials/detail_certificate_header.html' %}
{% endblock header %}

apps/project/specific/certificates/templates/certificate_detail.html
{% extends 'certificate_base.html' %}

{% load static i18n %}

{% block title %}{% trans 'Certificate Details' %}{% endblock title %}

{% block content %}
<div class="container mt-5">
    <div class="mx-auto">
        <div class="text-center mb-4">
            <h1>{% trans 'Suitability Verification' %}</h1>
        </div>
        <div class="row">
            <div class="col-md-4 text-center">
                <div class="row text-center">
                    <div class="col-sm-6 col-md-12 text-center">
                        <img src="{% static 'imgs/badge/certificate_badge.png' %}" alt="Certificate Badge" class="mb-4" style="max-width: 150px;">
                    </div>
                    <div class="col-sm-6 col-md-12">
                        <img id="qr-code" src="{{ qr_code }}" alt="QR Code" class="img-fluid" style="max-width: 150px;">
                    </div>
                </div>
            </div>

            <div class="col-md-8">
                <div>
                    <h2>{{ certificate.name }}</h2>
                    <p class="mb-1"><strong>{% trans 'ID Number:' %}</strong> {{ certificate.masked_document_number }}</p>
                    <p class="mb-1"><strong>{% trans 'Certificate ID:' %}</strong> {{ certificate.id }}</p>
                    {% if certificate.approved %}
                        <h3 class="text-success">{% trans 'Approved' %}</h3>
                    {% else %}
                        <h3 class="text-danger">{% trans 'Not Approved' %}</h3>
                    {% endif %}
                    <hr>
                    {% if certificate.approved %}
                        <p class="text-justify">
                                <strong>{{ certificate.name }}</strong>
                                {% trans 'with document number' %} {{ certificate.document_type }} {{ certificate.masked_document_number }}
                                {% blocktrans %}
                                    qualifies as a beneficiary, who has undergone a security study and accreditation of judicial records in accordance with the regulations in force in the Republic of Colombia; 
                                    and consequently, it does <strong>NOT</strong> present judicial or disciplinary records by the certifying entities authorized by Colombian legislation, 
                                    which affect its suitability for the date {% endblocktrans %} 
                                    {% if certificate.step == 1 %}
                                        {% trans 'September 20, 2024' %}.
                                    {% elif certificate.step == 2 %}
                                        {% trans 'October 20, 2024' %}.
                                    {% endif %}
                        </p>
                    {% else %}
                        <p class="text-justify">
                            <strong>{{ certificate.name }}</strong>
                            {% trans 'with document number' %} {{ certificate.document_type }} {{ certificate.masked_document_number }}
                            {% blocktrans %}
                                we inform you that, after the evaluation conducted, your security study <span class="text-danger">HAS NOT BEEN APPROVED</span> due to not meeting the suitability requirements according to the current security regulations.
                            {% endblocktrans %}
                        </p>
                    {% endif %}
                    <p>
                        <small>
                            {% trans 'We remind you that, in accordance with the provisions of the Habeas Data Law, all your personal data has been treated with due confidentiality and is protected under the strictest security standards, guaranteeing its integrity and privacy. Your data will be used exclusively for authorized purposes and within the framework of current data protection regulations.' %}
                        </small>
                    </p>
                    <p>
                        {% trans 'Stage:' %} {{ certificate.step }}
                        {% trans 'Status:' %} 
                        {% if certificate.approved %}
                            <i class="fas fa-check-circle text-success"></i>
                        {% else %}
                            <i class="fas fa-times-circle text-danger"></i>
                        {% endif %}
                    </p>
                    <div class="text-center">
                        <img id="barcode" src="{{ barcode }}" alt="Barcode" style="max-width: 100%;">
                    </div>
                </div>
            </div>
        </div>
        

        
        
        <div class="card-footer text-muted text-center mb-5">
            <p>
                <a href="https://www.propensionesabogados.com/" target="_blank" rel="noopener noreferrer">Propensiones Abogados S.A.S.</a> {% trans 'for the' %} <a href="https://fundacionleirion.com/" target="_blank" rel="noopener noreferrer">{% trans 'Leirion Foundation' %}</a> &copy; {% now "M Y" %}
            </p>
        </div>
    </div>
</div>

{% endblock content %}

apps/project/specific/certificates/templates/certificate_form_facade.html
{% extends 'certificate_base.html' %}

{% load static i18n %}

{% block title %}Formulario de certificación{% endblock title %}

{% block header %}{% endblock header %}

{% block content %}
    <div class="container" id="ff-compose"></div>
    <script async defer src="https://formfacade.com/include/104469299921200621343/form/1FAIpQLSe_O4oyV8DMColveUl9Ku9XMHvr49lJpAEF2qgZJBxTvGwRLg/bootstrap.js?div=ff-compose"></script>
{% endblock content %}

apps/project/specific/certificates/templates/certificate_input.html
{% extends 'certificate_base.html' %}

{% load static i18n %}

{% block title %}{% trans 'Verify your Certificate' %}{% endblock title %}

{% block content %}
<div class="container my-5">
    <h1 class="mb-4 text-center">{% trans 'Verify your Certificate' %}</h1>
    
    <form method="post" novalidate>
        {% csrf_token %}
        <div class="row justify-content-center">
            <div class="col-md-6">
                {{ form.non_field_errors }}
                <div class="form-floating mb-3">
                    <select name="{{ form.document_type.name }}"
                            id="floatingDocumentType"
                            class="form-select{% if form.document_type.errors %} is-invalid{% endif %}">
                        {% for choice in form.document_type.field.choices %}
                            <option value="{{ choice.0 }}"
                                    {% if choice.0 == form.document_type.value %}selected{% endif %}>
                                {{ choice.1 }}
                            </option>
                        {% endfor %}
                    </select>
                    <label for="floatingDocumentType">{{ form.document_type.label }}</label>
                    {% if form.document_type.errors %}
                        <div class="invalid-feedback">
                            {{ form.document_type.errors.as_text }}
                        </div>
                    {% endif %}
                </div>
                <div class="form-floating mb-3">
                    <input type="text"
                           name="{{ form.document_number.name }}"
                           id="floatingIDNumber"
                           class="form-control{% if form.document_number.errors %} is-invalid{% endif %}"
                           placeholder="C.C."
                           value="{{ form.document_number.value|default_if_none:'' }}">
                    <label for="floatingIDNumber">{{ form.document_number.label }}</label>
                    {% if form.document_number.errors %}
                        <div class="invalid-feedback">
                            {{ form.document_number.errors.as_text }}
                        </div>
                    {% endif %}
                </div>
                
                {% if messages %}
                    <div class="alert alert-danger" role="alert">
                        {% for message in messages %}
                        <div id="lockout-timer">
                            <p id="remaining-time">{{ message }} {% trans 'Please try again in' %} <span id="time-left">0</span> {% trans 'minutes.' %}</p>
                        </div>
                        {% endfor %}
                    </div>
                {% endif %}
                
            <button type="submit" class="btn btn-primary w-100">{% trans 'Verify' %}</button>
            </div>
        </div>
        
    </form>
</div>

<script>
    function updateRemainingTime() {
        fetch("{% url 'certificates:lockout_time' %}")
            .then(response => response.json())
            .then(data => {
                const remainingTime = data.remaining_time;
                if (remainingTime > 0) {
                    const minutes = Math.floor(remainingTime / 60);
                    const seconds = remainingTime % 60;
                    document.getElementById('time-left').innerText = `${minutes}:${seconds < 10 ? '0' + seconds : seconds}`;
                    document.getElementById('lockout-timer').style.display = 'block';
                } else {
                    document.getElementById('lockout-timer').style.display = 'none';
                }
            })
            .catch(error => console.error('Error fetching lockout time:', error));
    }

    document.addEventListener('DOMContentLoaded', function() {
        updateRemainingTime();
        setInterval(updateRemainingTime, 10*1000);
    });
</script>
{% endblock content %}

{% block footer %}
    {% include 'partials/footer.html' %}
{% endblock footer %}

apps/project/specific/certificates/templates/certificate_list.html
{% extends 'blank_template.html' %}

{% load static i18n %}

{% block title %}{% trans 'Certificate List' %}{% endblock title %}

{% block meta %}
    <meta charset="UTF-8">
    <meta http-equiv="PRAGMA" content="NO-CACHE" />
    <meta content="width=device-width, initial-scale=1.0" name="viewport"/>
    <meta content="text/html; charset=utf-8" http-equiv="Content-Type" />
    <meta content="{% trans 'Certificates | Fundación Leirion' %}" name="title" />
    <meta content="{% trans 'Certificates | Fundación Leirion' %}" property="og:title" />
    <meta content="{% static 'imgs/favicon/favicon-16x16.png' %}" property="og:image"/>
    <meta content="https://cbh.fundacionleirion.com/" property="og:url" />
    <meta content="Fundación Leirion" property="og:site_name" />
    <meta content="{% trans 'Fundación Leirion certificates' %}" property="og:description"/>
    <meta content="{% trans 'Fundación Leirion certificates' %}" name="description" />
{% endblock meta %}

{% block content %}
<div class="container mt-5">
    <h1 class="mb-4">{% trans 'Certificates' %}</h1>
    <form method="get" class="row mb-4 align-items-center">
        <div class="col-md-4">
            <div class="form-floating">
                <input type="text" name="q" class="form-control" id="floatingSearch" placeholder="Search" value="{{ request.GET.q }}">
                <label for="floatingSearch">{% trans 'Search by Name or ID Number' %}</label>
            </div>
        </div>
        <div class="col-md-2">
            <select name="step" class="form-select" id="stepFilter">
                <option value="">{% trans 'All Steps' %}</option>
                <option value="1" {% if request.GET.step == '1' %}selected{% endif %}>{% trans 'Step 1' %}</option>
                <option value="2" {% if request.GET.step == '2' %}selected{% endif %}>{% trans 'Step 2' %}</option>
            </select>
        </div>
        <div class="col-md-2">
            <select name="approved" class="form-select" id="approvedFilter">
                <option value="">{% trans 'All Status' %}</option>
                <option value="true" {% if request.GET.approved == 'true' %}selected{% endif %}>{% trans 'Approved' %}</option>
                <option value="false" {% if request.GET.approved == 'false' %}selected{% endif %}>{% trans 'Not Approved' %}</option>
            </select>
        </div>
        <div class="col-md-2">
            <button type="submit" class="btn btn-primary w-100">{% trans 'Search' %}</button>
        </div>
        <div class="col-md-2">
            <a href="{% url 'certificates:list' %}" class="btn btn-outline-secondary w-100">{% trans 'Clear Filters' %}</a>
        </div>
    </form>
    <p>Total: {{ total_displayed }}</p>
    
    <div class="table-responsive mb-5">
        <table class="table table-striped table-hover">
            <thead>
                <tr>
                    <th>
                        #
                        <a class="text-decoration-none" href="?{% if request.GET.q %}q={{ request.GET.q }}&{% endif %}step={{ request.GET.step }}&approved={{ request.GET.approved }}&order_by=default_order&order_dir={% if order_by != 'default_order' or order_dir == 'desc' %}asc{% else %}desc{% endif %}">
                            {% if order_by == 'default_order' %}
                                <i class="fas fa-sort-{% if order_dir == 'asc' %}up{% else %}down{% endif %}"></i>
                            {% else %}
                                <i class="fas fa-sort"></i>
                            {% endif %}
                        </a>
                    </th>
                    <th>
                        {% trans 'Name' %}
                        <a class="text-decoration-none" href="?{% if request.GET.q %}q={{ request.GET.q }}&{% endif %}step={{ request.GET.step }}&approved={{ request.GET.approved }}&order_by=name&order_dir={% if order_by != 'name' or order_dir == 'desc' %}asc{% else %}desc{% endif %}">
                            {% if order_by == 'name' %}
                                <i class="fas fa-sort-{% if order_dir == 'asc' %}up{% else %}down{% endif %}"></i>
                            {% else %}
                                <i class="fas fa-sort"></i>
                            {% endif %}
                        </a>
                    </th>
                    <th>
                        {% trans 'Document Number' %}
                        <a class="text-decoration-none" href="?{% if request.GET.q %}q={{ request.GET.q }}&{% endif %}step={{ request.GET.step }}&approved={{ request.GET.approved }}&order_by=document_number&order_dir={% if order_by != 'document_number' or order_dir == 'desc' %}asc{% else %}desc{% endif %}">
                            {% if order_by == 'document_number' %}
                                <i class="fas fa-sort-{% if order_dir == 'asc' %}up{% else %}down{% endif %}"></i>
                            {% else %}
                                <i class="fas fa-sort"></i>
                            {% endif %}
                        </a>
                    </th>
                    <th>{% trans 'Certificate ID' %}</th>
                    <th>
                        {% trans 'Step' %}
                        <a class="text-decoration-none" href="?{% if request.GET.q %}q={{ request.GET.q }}&{% endif %}step={{ request.GET.step }}&approved={{ request.GET.approved }}&order_by=step&order_dir={% if order_by != 'step' or order_dir == 'desc' %}asc{% else %}desc{% endif %}">
                            {% if order_by == 'step' %}
                                <i class="fas fa-sort-{% if order_dir == 'asc' %}up{% else %}down{% endif %}"></i>
                            {% else %}
                                <i class="fas fa-sort"></i>
                            {% endif %}
                        </a>
                    </th>
                    <th>
                        {% trans 'Approved Status' %}
                        <a class="text-decoration-none" href="?{% if request.GET.q %}q={{ request.GET.q }}&{% endif %}step={{ request.GET.step }}&approved={{ request.GET.approved }}&order_by=approved&order_dir={% if order_by != 'approved' or order_dir == 'desc' %}asc{% else %}desc{% endif %}">
                            {% if order_by == 'approved' %}
                                <i class="fas fa-sort-{% if order_dir == 'asc' %}up{% else %}down{% endif %}"></i>
                            {% else %}
                                <i class="fas fa-sort"></i>
                            {% endif %}
                        </a>
                    </th>
                    <th></th>
                    <th></th>
                </tr>
            </thead>
            <tbody class="table-group-divider">
                {% for certificate in certificates %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ certificate.name }}</td>
                    <td>{{ certificate.document_number }}</td>
                    <td>{{ certificate.id }}</td>
                    <td>{{ certificate.step }}</td>
                    <td>
                        {% if certificate.approved %}
                            <i class="fas fa-check-circle text-success"></i>
                        {% else %}
                            <i class="fas fa-times-circle text-danger"></i>
                        {% endif %}
                    </td>
                    <td>
                        <a href="{% url 'certificates:detail' certificate.id %}" class="btn btn-sm btn-outline-success">{% trans 'View' %}</a>
                    </td>
                    <td>
                        <a href="{% url 'admin:certificates_certificatemodel_change' certificate.id %}" class="btn btn-sm btn-outline-warning">{% trans 'Edit' %}</a>
                    </td>
                </tr>
                {% empty %}
                <tr>
                    <td colspan="8" class="text-center">{% trans 'No certificates found.' %}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock content %}