app_core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path, re_path

from apps.common.utils.views import handler400 as h400
from apps.common.utils.views import handler403 as h403
from apps.common.utils.views import handler404 as h404
from apps.common.utils.views import handler500 as h500

admin_url = settings.ADMIN_URL
custom_apps = settings.CUSTOM_APPS
utils_path = settings.UTILS_PATH

apps_urls = [path('', include(f'{app}.urls')) for app in custom_apps]

handler400 = h400

handler403 = h403

handler404 = h404

handler500 = h500

third_party_urls = [
    re_path(
        r'^rosetta/',
        include('rosetta.urls')
    ),
]

admin_urls = [
    path(admin_url, admin.site.urls),
]

urlpatterns = admin_urls + apps_urls + third_party_urls

if settings.DEBUG:
    urlpatterns += static(
        settings.STATIC_URL,
        document_root=settings.STATIC_ROOT
    )
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )

apps/project/specific/sales/urls.py
from django.urls import path

from .views import SalesView

app_name = 'sales'

urlpatterns = [
    path(
        'sales/',
        SalesView.as_view(),
        name='sales'
    )
]

apps/project/specific/sales/models.py
from auditlog.registry import auditlog
from django.db import models
from django.utils.translation import gettext_lazy as _

from apps.common.utils.models import (EncryptedCharField,
                                      EncryptedDecimalField,
                                      EncryptedIntegerField, TimeStampedModel)
from apps.project.specific.assets.models import AssetModel


class SalesModel(TimeStampedModel):
    class SalesTypeChoices(models.TextChoices):
        DIRECT_SALES = "DS", _('Direct Sales')
        RD = 'RD', _('RD')
        OTHER = 'O', _('Other')

    class BuyerTypeChoices(models.TextChoices):
        BANK = 'B', _('Bank')
        ORGANIZATION = 'ON', _('Organization')
        PRIVATE = 'P', _('Private')
        OTHER = 'O', _('Other')

    class CurrencyTypeChoices(models.TextChoices):
        AED = 'AED', _('AED, United Arab Emirates Dirham')
        ARS = 'ARS', _('ARS, Argentine Peso')
        AUD = 'AUD', _('AUD, Australian Dollar')
        BRL = 'BRL', _('BRL, Brazilian Real')
        CAD = 'CAD', _('CAD, Canadian Dollar')
        CHF = 'CHF', _('CHF, Swiss Franc')
        CNY = 'CNY', _('CNY, Chinese Yuan')
        COP = 'COP', _('COP, Colombian Peso')
        DKK = 'DKK', _('DKK, Danish Krone')
        EUR = 'EUR', _('EUR, Euro')
        GBP = 'GBP', _('GBP, British Pound Sterling')
        HKD = 'HKD', _('HKD, Hong Kong Dollar')
        ILS = 'ILS', _('ILS, Israeli New Shekel')
        INR = 'INR', _('INR, Indian Rupee')
        JPY = 'JPY', _('JPY, Japanese Yen')
        KRW = 'KRW', _('KRW, South Korean Won')
        MXN = 'MXN', _('MXN, Mexican Peso')
        MYR = 'MYR', _('MYR, Malaysian Ringgit')
        NOK = 'NOK', _('NOK, Norwegian Krone')
        NZD = 'NZD', _('NZD, New Zealand Dollar')
        PLN = 'PLN', _('PLN, Polish Zloty')
        RUB = 'RUB', _('RUB, Russian Ruble')
        SAR = 'SAR', _('SAR, Saudi Riyal')
        SEK = 'SEK', _('SEK, Swedish Krona')
        SGD = 'SGD', _('SGD, Singapore Dollar')
        THB = 'THB', _('THB, Thai Baht')
        TRY = 'TRY', _('TRY, Turkish Lira')
        TWD = 'TWD', _('TWD, New Taiwan Dollar')
        USD = 'USD', _('USD, United States Dollar')
        ZAR = 'ZAR', _('ZAR, South African Rand')
        ZWD = 'ZWD', _('ZWD, Zimbabwe Dollar')

    asset = models.ForeignKey(
        AssetModel,
        on_delete=models.CASCADE,
        related_name="sales_bond",
        verbose_name=_("asset")
    )

    buyer_type = models.CharField(
        _("buyer type"),
        max_length=3,
        choices=BuyerTypeChoices.choices,
        default=BuyerTypeChoices.PRIVATE
    )

    buyer_name = EncryptedCharField(
        _("buyer name"),
        max_length=255
    )

    buyer_country = models.CharField(
        _('country code'),
        max_length=50,
        default='US'
    )

    amount_sold = EncryptedIntegerField(
        _("amount sold"),
        max_length=255
    )

    sales_type = models.CharField(
        _("sales type"),
        max_length=3,
        choices=SalesTypeChoices.choices,
        default=SalesTypeChoices.DIRECT_SALES
    )

    sale_value = EncryptedDecimalField(
        _("sale value"),
        max_length=255
    )

    sale_currency = models.CharField(
        _("currency"),
        max_length=4,
        choices=CurrencyTypeChoices.choices,
        default=CurrencyTypeChoices.USD
    )

    def __str__(self) -> str:
        return f"{self.asset.name}"

    class Meta:
        db_table = "apps_project_specific_sales_sales"
        verbose_name = _("Sale")
        verbose_name_plural = _("Sales")


auditlog.register(
    SalesModel,
    serialize_data=True
)

apps/common/core/forms.py
from django import forms


class KeyPrefixForm(forms.Form):
    key_prefix = forms.CharField(
        max_length=6,
        label='Enter first 6 characters of the key'
    )

apps/project/specific/sales/views.py
import logging

from cryptography.fernet import Fernet
from django.conf import settings
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse
from django.shortcuts import redirect
from django.views.generic import TemplateView

from apps.common.core.forms import KeyPrefixForm

from .models import SalesModel

logger = logging.getLogger(__name__)


class SalesView(LoginRequiredMixin, TemplateView):
    group_required = settings.SALES_GROUP
    redirect_url = "/"
    template_name = 'sales_info.html'

    def __init__(self, *args, **kwargs):
        self.cipher = Fernet(settings.ENCODED_KEY)
        
        logger.warning(
            f'encoded key | {settings.ENCODED_KEY}'
        )
        
        logger.warning(
            f'encoded key | {self.cipher}'
        )
        
        super().__init__(*args, **kwargs)

    def decrypt(self, value):
        if value is None:
            return value

        return self.cipher.decrypt(
            value.encode('utf-8')
        ).decode('utf-8')

    def get(self, request, *args, **kwargs):
        key_prefix = request.session.get('key_prefix', None)
        if not key_prefix:
            return self.render_to_response({'form': KeyPrefixForm()})

        key: str = settings.SECRET_KEY[:32]
        if not key.startswith(key_prefix):
            return HttpResponse("Invalid key", status=403)

        sales_data = SalesModel.objects.all()

        for sale in sales_data:
            sale.buyer_name = self.decrypt(sale.buyer_name) or ""
            sale.amount_sold = self.decrypt(sale.amount_sold) or ""
            sale.sale_value = self.decrypt(sale.sale_value) or ""

        return self.render_to_response({'sales_data': sales_data})

    def post(self, request, *args, **kwargs):
        form = KeyPrefixForm(request.POST)
        if form.is_valid():
            key_prefix = form.cleaned_data['key_prefix']
            key = settings.SECRET_KEY[:32]

            if key.startswith(key_prefix):
                request.session['key_prefix'] = key_prefix
                return redirect('sales:sales')
            else:
                form.add_error('key_prefix', 'Invalid key')
        return self.render_to_response({'form': form})

apps/project/specific/sales/templates/sales_info.html
{% extends 'blank_template.html' %}

{% load static i18n currency_format %}
{% get_current_language as LANGUAGE_CODE %}
{% get_available_languages as LANGUAGES %}

{% block main %}
<div class="container mt-2">
    {% if request.session.key_prefix %}
    <style>
        tr > th {
            text-align: center;
        }
    </style>
        <h2 class="text-capitalize">{% trans 'Sales Information' %}</h2>
        <table class="table table-striped table-bordered table-hover">
            <thead>
                <tr>
                    <th class="text-capitalize">{% trans 'Assets' %}</th>
                    <th class="text-capitalize">{% trans 'Buyer Type' %}</th>
                    <th class="text-capitalize">{% trans 'Buyer Name' %}</th>
                    <th class="text-capitalize">{% trans 'Country' %}</th>
                    <th class="text-capitalize">{% trans 'Amount Sold' %}</th>
                    <th class="text-capitalize">{% trans 'Sales Type' %}</th>
                    <th class="text-capitalize">{% trans 'Sale Value' %}</th>
                    <th class="text-capitalize">{% trans 'Currency' %}</th>
                    <th class="text-capitalize">{% trans 'Created' %}</th>
                    <th class="text-capitalize">{% trans 'Updated' %}</th>
                </tr>
            </thead>
            <tbody>
                {% for sale in sales_data %}
                <tr>
                    <td>{{ sale.assets }}</td>
                    <td>{{ sale.get_buyer_type_display }}</td>
                    <td>{{ sale.buyer_name }}</td>
                    <td>{{ sale.buyer_country }}</td>
                    <td>{{ sale.amount_sold }}</td>
                    <td>{{ sale.get_sales_type_display }}</td>
                    <td>{{ sale.sale_value|currency }}</td>
                    <td>{{ sale.sale_currency }}</td>
                    <td>{{ sale.created|date:"d M Y H:i" }}</td>
                    <td>{{ sale.updated|date:"d M Y H:i" }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    {% else %}
        <h2>{% trans 'Key Validation' %}</h2>
        <form method="post">
            {% csrf_token %}
            <div class="form-floating mb-3">
                <input type="text" name="key_prefix" class="form-control" maxlength="6" required id="id_key_prefix" placeholder="******">
                <label for="id_key_prefix">{% trans 'Enter the key:' %}</label>
                {% if form.errors %}
                    <b style="color: var(--bs-danger-text-emphasis)">{{ form.key_prefix.errors }}</b>
                {% endif %}
            </div>
            <div class="d-grid gap-2">
                <button type="submit" class="btn btn-outline-primary">{% trans 'Submit' %}</button>
            </div>
        </form>
    {% endif %}
</div>
{% endblock main %}