app_core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path, re_path

from apps.common.utils.views import handler400 as h400
from apps.common.utils.views import handler403 as h403
from apps.common.utils.views import handler404 as h404
from apps.common.utils.views import handler500 as h500

admin_url = settings.ADMIN_URL
custom_apps = settings.CUSTOM_APPS
utils_path = settings.UTILS_PATH

apps_urls = [path('', include(f'{app}.urls')) for app in custom_apps]

handler400 = h400

handler403 = h403

handler404 = h404

handler500 = h500

third_party_urls = [
    re_path(
        r'^rosetta/',
        include('rosetta.urls')
    ),
]

admin_urls = [
    path(admin_url, admin.site.urls),
]

urlpatterns = admin_urls + apps_urls + third_party_urls

if settings.DEBUG:
    urlpatterns += static(
        settings.STATIC_URL,
        document_root=settings.STATIC_ROOT
    )
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )

apps/common/core/urls.py
from django.urls import include, path

from apps.common.core.views import IndexTemplateView

app_name = 'core'

urlpatterns = [
    path(
        '',
        IndexTemplateView.as_view(),
        name='index'
    )
]

apps/project/common/account/urls.py
from django.urls import path

from .views import UserLoginView, UserLogoutView, UserRegisterView

app_name = "account"

urlpatterns = [
    path(
        'accounts/register/',
        UserRegisterView.as_view(),
        name='register'
    ),
    path(
        'accounts/logout/',
        UserLogoutView.as_view(),
        name='logout'
    ),
    path(
        'accounts/login/',
        UserLoginView.as_view(),
        name='login'
    )
]

apps/project/specific/certificates/urls.py
from django.urls import path

from .views import CertificateInputView, CertificateDetailView, CertificateListView, CertificateFormFacadeTemplateView, LockoutTimeView

app_name = 'certificates'

urlpatterns = [
    path('certificate/', CertificateInputView.as_view(), name='input'),
    path('certificate/form/', CertificateFormFacadeTemplateView.as_view(), name='form'),
    path('certificate/<uuid:pk>/', CertificateDetailView.as_view(), name='detail'),
    path('certificate/list/', CertificateListView.as_view(), name='list'),
    path('lockout-time/', LockoutTimeView.as_view(), name='lockout_time'),
]

apps/project/specific/sales/urls.py
from django.urls import path

from .views import SalesView

app_name = 'sales'

urlpatterns = [
    path(
        'sales/',
        SalesView.as_view(),
        name='sales'
    )
]

apps/common/core/models.py
from auditlog.registry import auditlog
from django.db import models
from django.utils.translation import gettext_lazy as _

from apps.common.utils.models import TimeStampedModel


class IPBlockedModel(TimeStampedModel):
    class ReasonsChoices(models.TextChoices):
        SERVER_HTTP_REQUEST = 'RA', _('Attempts to obtain forbidden urls')
        SECURITY_KEY_ATTEMPTS = 'SK', _(
            'Multiple failed security key entry attempts'
        )

    is_active = models.BooleanField(
        _("is blocked"),
        default=True
    )

    current_ip = models.CharField(
        _('current user ip'),
        max_length=150
    )

    reason = models.CharField(
        _("reason"),
        max_length=4,
        choices=ReasonsChoices.choices,
        default=ReasonsChoices.SERVER_HTTP_REQUEST
    )

    def __str__(self):
        return self.current_ip

    class Meta:
        db_table = 'apps_common_core_iptoblock'
        verbose_name = 'IP Blocked'
        verbose_name_plural = 'IPs Blocked'


auditlog.register(
    IPBlockedModel,
    serialize_data=True
)

apps/common/core/forms.py
from django import forms


class KeyPrefixForm(forms.Form):
    key_prefix = forms.CharField(
        max_length=6,
        label='Enter first 6 characters of the key'
    )

apps/common/core/views.py
from datetime import timedelta

from django.conf import settings
from django.http import HttpResponseForbidden
from django.shortcuts import redirect
from django.utils import timezone
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_protect
from django.views.generic import TemplateView

from apps.common.core.models import IPBlockedModel
from apps.project.common.account.models import UserLoginAttemptModel

from .forms import KeyPrefixForm


# class KeyPrefixRequiredMixin:
#     MAX_ATTEMPTS = settings.MAX_KEY_ATTEMPS
#     ATTEMPT_RESET_TIME = timedelta(minutes=3600)

#     @method_decorator(csrf_protect)
#     def dispatch(self, request, *args, **kwargs):
#         key_prefix = request.session.get('key_prefix', None)
#         user_ip = request.META['REMOTE_ADDR']

#         if IPBlockedModel.objects.filter(current_ip=user_ip, is_active=True).exists():
#             return HttpResponseForbidden("Your IP has been blocked due to too many incorrect attempts.")

#         if not key_prefix:
#             return self.render_to_response({'form': KeyPrefixForm()})

#         key = settings.SECRET_KEY[:32]
#         if not key.startswith(key_prefix):
#             user_login_attempt, created = UserLoginAttemptModel.objects.get_or_create(
#                 user=request.user
#             )

#             if timezone.now() - user_login_attempt.last_attempt > self.ATTEMPT_RESET_TIME:
#                 user_login_attempt.attempts = 0

#             user_login_attempt.attempts += 1
#             user_login_attempt.save()

#             if user_login_attempt.attempts >= self.MAX_ATTEMPTS:
#                 IPBlockedModel.objects.create(
#                     current_ip=user_ip,
#                     reason=IPBlockedModel.ReasonsChoices.SECURITY_KEY_ATTEMPTS
#                 )
#                 user_login_attempt.attempts = 0
#                 user_login_attempt.save()
#                 return HttpResponseForbidden("Your IP has been blocked due to too many incorrect attempts.")

#             return HttpResponseForbidden("Invalid key")

#         return super().dispatch(request, *args, **kwargs)

#     def post(self, request, *args, **kwargs):
#         form = KeyPrefixForm(request.POST)
#         if form.is_valid():
#             key_prefix = form.cleaned_data['key_prefix']
#             key = settings.SECRET_KEY[:32]

#             if key.startswith(key_prefix):
#                 request.session['key_prefix'] = key_prefix

#                 next_url = self.request.GET.get('next', 'core:index')
#                 return redirect(next_url)
#             else:
#                 form.add_error('key_prefix', 'Invalid key')

#         return self.render_to_response({'form': form})


class IndexTemplateView(TemplateView):
    template_name = "page/index.html"

apps/common/core/templates/partials/footer.html
{% load i18n %}

<footer class="fixed-bottom">
    <div class="container">
        <div class="justify-content-center">
            <p>© {% now "M Y" %}</p>
        </div>
    </div>
</footer>

apps/common/core/templates/partials/header.html
{% load static i18n %}

<header class="container-fluid">
    {% include 'partials/nav.html' %}
</header>

apps/common/core/templates/partials/nav.html
{% load static i18n %}

<nav class="navbar bg-body-tertiary navbar-expand-lg sticky-top">
  <div class="container">
    <a class="navbar-brand text-capitalize" href="{% url 'core:index' %}">{% trans 'CHB' %}</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
    <div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasNavbar" aria-labelledby="offcanvasNavbarLabel">
      <div class="offcanvas-header">
        <h5 class="offcanvas-title text-capitalize" id="offcanvasNavbarLabel">{% trans 'CHB' %}</h5>
        <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
      </div>
      <div class="offcanvas-body">
        <ul class="navbar-nav justify-content-center flex-grow-1 pe-3">
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" role="button" data-bs-toggle="dropdown" aria-expanded="false">{% trans 'Certificates' %}</a>
            <ul class="dropdown-menu">
              <li>
                <a class="dropdown-item text-capitalize" href="{% url 'certificates:input' %}">{% trans 'Verify' %}</a>
              </li>
              {% if request.user.is_authenticated and request.user.is_staff %}
                <li>
                  <a class="dropdown-item text-capitalize" href="{% url 'certificates:list' %}">{% trans 'List' %}</a>
                </li>
                <li>
                  <a class="dropdown-item text-capitalize" href="{% url 'certificates:form' %}">{% trans 'Form' %}</a>
                </li>
              {% endif %}
            </ul>
          </li>
          {% comment %}
          <li class="nav-item">
            <a class="nav-link text-capitalize active" href="{% url 'core:index' %}">{% trans 'Home' %}</a>
          </li>
          <li class="nav-item">
            <a class="nav-link text-capitalize" href="{% url 'core:index' %}">{% trans 'Bonds' %}</a>
          </li>
          <li class="nav-item">
            <a class="nav-link text-capitalize" href="{% url 'core:index' %}">{% trans 'Categories' %}</a>
          </li>
          <li class="nav-item">
            <a class="nav-link text-capitalize" href="{% url 'core:index' %}">{% trans 'Locations' %}</a>
          </li>
          <li class="nav-item">
            <a class="nav-link text-capitalize" href="{% url 'sales:sales' %}">{% trans 'Sales' %}</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" role="button" data-bs-toggle="dropdown" aria-expanded="false">{% trans 'Reports' %}</a>
            <ul class="dropdown-menu">
              <li>
                <a class="dropdown-item text-capitalize" href="{% url 'core:index' %}">{% trans 'Bonds' %}</a>
              </li>
              <li>
                <a class="dropdown-item text-capitalize" href="{% url 'core:index' %}">{% trans 'Sales' %}</a>
              </li>
            </ul>
          </li>
          {% endcomment %}
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" role="button" data-bs-toggle="dropdown" aria-expanded="false">{% trans 'Language' %}</a>
            <ul class="dropdown-menu">
              {% for lang in LANGUAGES %}
                <li>
                    <a class="dropdown-item text-capitalize" href="{% url 'set_language' %}?lang={{ lang.0 }}">
                        {{ lang.1 }}
                    </a>
                </li>
              {% endfor %}
            </ul>
          </li>
        </ul>
        
        {% if request.user.is_authenticated %}
          <a class="btn btn-outline-danger my-2 my-sm-0 text-capitalize" href="{% url 'account:logout' %}">{% trans 'Logout' %}</a>
          
          {% if request.user.is_staff %}
            <a class="btn btn-outline-warning m-2 my-sm-0 text-capitalize" href="{% url 'admin:index' %}">{% trans 'Admin' %}</a>
          {% endif %}
            
        {% else %}
          <a class="btn btn-outline-success my-2 my-sm-0 text-capitalize" href="{% url 'account:login' %}">{% trans 'Login' %}</a>
        {% endif %}
      </div>
    </div>
  </div>
</nav>